# -*- coding: utf-8 -*-
"""Python tutorial 02-oct-2020.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lx3szoUurXY2QGeRbtRZ_VMb5OxfYXnX
"""

print("Hello Good morning")
#Basic Syntax

#variables
x=5
print(x)

y23='anusha' #starts with only letters can't starts with numbers and [0-9 a-z _]
Y23='anusha'
print(y23)
print(Y23)

x,y,z="str1","str2","str3"
print(x)
print(y)
print(z)
x=y=z="org"
print(x)
print(y)
print(z)

x="anu"
y="sha"
print(x+y)
x=3
y=5
print(x+y)

# data types
# text tye,number .sequence mapping set boolean binary

x="hello world"
print(x)
print(type(x))
y=2
print(y)
print(type(y))
z=20.45
print(type(z))
print(z)
x=["apple","grape"]
print(x)
print(type(x))
x=("apple","grape")
print(x)
print(type(x))
x=range(8)
print(x)
print(type(x))



y={"anu","apple","anu","apple"}
print(y)
print(type(y))

x=True
y=False
print(x,y)
print(x)
print(y)
print(type(x))
print(type(y))

x=b"Hello"
print(x)
print(type(x))

x={"age1":"anu","age":20,"name":123}
print(x)
print(type(x))

#starting of about section

print("")
x="anu"
x=5
x=['','',]
x=('','')
print(x)
print('')
print(7)
#end of about section
#start of

